// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maiaaraujo5/udp-chat/internal/app/server/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// DeleteMessage is an autogenerated mock type for the DeleteMessage type
type DeleteMessage struct {
	mock.Mock
}

// Execute provides a mock function with given fields: parentCtx, message
func (_m *DeleteMessage) Execute(parentCtx context.Context, message *model.Message) error {
	ret := _m.Called(parentCtx, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Message) error); ok {
		r0 = rf(parentCtx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
