// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maiaaraujo5/udp-chat/internal/app/server/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// Recover is an autogenerated mock type for the Recover type
type Recover struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *Recover) Execute(ctx context.Context) ([]model.Message, error) {
	ret := _m.Called(ctx)

	var r0 []model.Message
	if rf, ok := ret.Get(0).(func(context.Context) []model.Message); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
